name: "Setup pipeline environment"
description: "Install commands: tccli coscli tdlc scf ..."

# inputs:
  # node-version:
  #   description: 'Node.js version'
  #   required: false
  #   default: 'lts'
  # python-version:
  #   description: 'python version'
  #   required: false
  #   default: 'latest'

runs:
  using: composite
  steps:
    # - uses: actions/setup-node@v5
    #   # https://github.com/actions/setup-node
    #   with:
    #     node-version: ${{ inputs.node-version }}        # 可写 18 / 16 / lts/* / 具体 semver
    #     cache: 'npm'              # 或 'yarn' / 'pnpm'，自动缓存依赖
    #     cache-dependency-path: 'pipeline/package-lock.json'


    # - uses: actions/setup-python@v6
    #   with:
    #     python-version: ${{ inputs.python-version }}   # 支持 3.8 - 3.13、3.x、latest
    #     cache: 'pip' # caching pip dependencies
    #     cache-dependency-path: 'pipeline/requirements.txt'
    - name: Install tools
      shell: bash -el {0}
      run: sudo apt-get update -yq && sudo apt-get install -yq wget curl vim sshpass

    - name: Cache cos cli
      id:   cache-cos-cli
      uses: actions/cache@v4
      with:
        path: /tmp/coscli-linux-amd64
        key: cos-cli

    - name: Download cos-cli (if cache miss)
      if: steps.cache-cos-cli.outputs.cache-hit != 'true'
      shell: bash -el {0}
      run: |
        wget https://cosbrowser.cloud.tencent.com/software/coscli/coscli-linux-amd64 -P /tmp/

    - name: InstallTools coscli
      shell: bash -el {0}
      run: |
        # if ! command -v scf; then
        #   echo "########### install scf ###########"
        #   time npm install -g --no-fund  serverless-cloud-framework
        # fi

        # time pip3 install jinja2
        # if ! command -v tccli; then
        #   echo "########### install tccli ###########"
        #   time sudo pip3 install tccli # --break-system-packages
        #   which tccli
        # fi

        # 将路径添加到 GITHUB_ENV,对后续所有步骤生效
        # echo "/usr/local/bin" >> $GITHUB_PATH
        if ! command -v coscli ; then
          echo "########### install coscli ###########"
          # wget https://cosbrowser.cloud.tencent.com/software/coscli/coscli-linux-amd64
          sudo install -m 755 /tmp/coscli-linux-amd64 /usr/bin/coscli
        fi
