# This is a basic workflow to help you get started with Actions

name: "[ 13 ] kind Setup k8s cluster"

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner Agent'
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - self-hosted
          - ubuntu-latest

      kindest_node_tag:
        description: 'supported kindest/node:tag'
        required: true
        default: '1.35.0'
        type: choice
        options:
          - '1.34.0'
          - '1.35.0'          
      # VMs:
      #   description: 'VM list JSON array'
      #   required: true
      #   type: string
      #   default: '["10.10.10.11", "10.10.10.101", "10.10.10.102"]'   

env:
  TAILSCALE_HOST: pve
  TAILSCALE_NET: taile80cb.ts.net

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup:
    name: 🚀 Deploy k8s via kind
    # The type of runner that the job will run on
    # runs-on: [self-hosted]
    # runs-on: ubuntu-latest
    runs-on: ${{ github.event.inputs.runner }}
    permissions:
      id-token: write   # 让 GitHub 颁发 OIDC
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check if already ssh key-based
        id: check-ssh
        run: |
          set +e
          test -d ~/.ssh || mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} >> ~/.ssh/known_hosts
          ssh -o BatchMode=yes -o ConnectTimeout=5  root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} exit
          if [ $? -eq 0 ]; then
            echo "keyless=true" >> $GITHUB_OUTPUT
          else
            echo "keyless=false" >> $GITHUB_OUTPUT
          fi      

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      # 1️⃣  把 Runner 接入 tailnet
      - name: setup Tailscale Connect (if needed)
        if: steps.check-ssh.outputs.keyless != 'true'
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret:    ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci     # 与 ACL 中的 tag 保持一致
          version: latest # https://pkgs.tailscale.com/stable/#static
          use-cache: 'true'

      # - name: set tailscale ssh
      #   run: |
      #     # pveHost=$(tailscale status --json | jq -r '.Self.HostName' )
      #     # sudo tailscale up --advertise-tags=tag:gh --accept-routes --hostname=${pveHost}
      #     # tailscale status
      #     test -d ~/.ssh || mkdir -p ~/.ssh
      #     ssh-keyscan -H ${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} >> ~/.ssh/known_hosts
      #     echo ssh root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} "true"
      #     ssh root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} "true"

      - name: get kind latest version
        run: |
          function get_github_latest_release() {
            curl --silent "https://api.github.com/repos/$1/releases/latest" | # Get latest release from GitHub api
                grep '"tag_name":' |                                          # Get tag line
                sed -E 's/.*"([^"]+)".*/\1/'                                  # Pluck JSON value
          }

          # get the latest version of kind
          kind_ver=$(get_github_latest_release "kubernetes-sigs/kind")
          # curl -SLO "${GHPROXY}https://github.com/kubernetes-sigs/kind/releases/download/${kind_ver}/kind-linux-amd64"
          echo "KIND_VERSION=${kind_ver}" >> $GITHUB_ENV

          # install kind-linux-amd64 for ingress and gateway and loadbalancer
          version=$(get_github_latest_release "kubernetes-sigs/cloud-provider-kind")
          echo "CPK_VERSION=${version}" >> $GITHUB_ENV
          # curl -SLO "${GHPROXY}https://github.com/kubernetes-sigs/cloud-provider-kind/releases/download/${version}/cloud-provider-kind_${version/v/}_linux_amd64.tar.gz"
          # tar -xvf cloud-provider-kind_${version/v/}_linux_amd64.tar.gz
          # sudo install cloud-provider-kind /usr/local/bin

      - name: Cache kind binary
        id:   cache-kind
        uses: actions/cache@v4
        with:
          path: /tmp/kind
          key: kind-${{ env.KIND_VERSION }}-${{ env.CPK_VERSION }}

      - name: Download kind (if cache miss)
        if: steps.cache-kind.outputs.cache-hit != 'true'
        run: |
          wget -q "${GHPROXY}https://github.com/kubernetes-sigs/kind/releases/download/${{ env.KIND_VERSION }}/kind-linux-amd64" -O "/tmp/kind/kind"
          wget -q "${GHPROXY}https://github.com/kubernetes-sigs/cloud-provider-kind/releases/download/${{ env.CPK_VERSION }}/cloud-provider-kind_${{ env.CPK_VERSION/v/ }}_linux_amd64.tar.gz" -O "/tmp/kind/cloud-provider-kind.tar.gz"

      - name: sync kind binary to remote
        # if: steps.ache-airgap-images.outputs.cache-hit != 'true'
        run: |
 
          cat > create-kind-cluster.sh <<EOF
          cat << ENDOF | kind create cluster --name kind \
          --image registry.cn-beijing.aliyuncs.com/my-dockermirrors/kindest_node:v${{ github.event.inputs.kindest_node_tag }} --config=-
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
          - role: worker
          # - role: worker
          ENDOF
          EOF

          for pkg in /tmp/kind/kind /tmp/kind/cloud-provider-kind.tar.gz create-kind-cluster.sh
          do
            # ssh-keygen -f "~/.ssh/known_hosts" -R ${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }}
            # ssh-keyscan -H ${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} >> ~/.ssh/known_hosts
            echo "Sync ${pkg} from runner to ${{ env.TAILSCALE_HOST }} ..."         
            rsync --rsync-path="sudo rsync" -e  'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -avz --partial --progress --inplace $pkg root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }}:/root/
            # scp $pkg root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }}:/root/
          done



      - name: install kind and cloud-provider-kind on remote
        run: |
          # alias ssh='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} "pwd"
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} "install -m 755 kind /usr/local/bin"
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} "tar -xvf cloud-provider-kind.tar.gz ; install -m 755 cloud-provider-kind /usr/local/bin"
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} "tmux new-session -d -s kind '/usr/local/bin/cloud-provider-kind'"
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} "bash create-kind-cluster.sh; kubectl get nodes -o wide"

