# This is a basic workflow to help you get started with Actions

name: "[ 14 ] kubespray Setup k8s cluster"

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner Agent'
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - self-hosted
          - ubuntu-latest

      skip_file:
        description: 'Skip OFFLINE file download'
        required: true
        default: true
        type: boolean

      skip_image::
        description: 'Skip OFFLINE images sync'
        required: true
        default: true
        type: boolean

      vm_user:
        description: 'VM Guest: OS User'
        required: true
        default: vagrant
        type: choice
        options:
          - vagrant
          - root

      VMs:
        description: 'VM list JSON array'
        required: true
        type: string
        default: '["10.10.10.11", "10.10.10.101", "10.10.10.102"]'

      # k8s_version:
      #   description: 'supported stable k8s version https://kubernetes.io/releases/'
      #   required: true
      #   default: '1.34'
      #   type: choice
      #   options:
      #     - '1.32'
      #     - '1.33'
      #     - '1.34'
      #     - '1.35'

env:
  TAILSCALE_HOST: pve
  TAILSCALE_NET: taile80cb.ts.net
  # VM_TEMPLATE_ID: 2009 # vm模板的ID
  # VM_CIDR: 10.10.10 # vmbr0 vmbr1 的网段
  # MASTER_IP: 10.10.10.11
  # NODE01_IP: 10.10.10.101
  # NODE02_IP: 10.10.10.102
  VMs: ${{ github.event.inputs.VMs }}
  VM_USER: ${{ github.event.inputs.vm_user }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup:
    name: 🚀 Deploy k8s via kubespray
    # The type of runner that the job will run on
    # runs-on: [self-hosted]
    # runs-on: ubuntu-latest
    runs-on: ${{ github.event.inputs.runner }}
    permissions:
      id-token: write   # 让 GitHub 颁发 OIDC
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      - name: Install tools
        run: |
          sudo apt-get update -yq && sudo apt-get install -yq sshpass skopeo
        #   wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        #   sudo install -m 755 yq_linux_amd64 /usr/bin/yq

      - name: Check if already ssh key-based
        id: check-ssh
        run: |
          set +e
          test -d ~/.ssh || mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} >> ~/.ssh/known_hosts
          ssh -o BatchMode=yes -o ConnectTimeout=5  root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} exit
          if [ $? -eq 0 ]; then
            echo "keyless=true" >> $GITHUB_OUTPUT
          else
            echo "keyless=false" >> $GITHUB_OUTPUT
          fi      

      # 1️⃣  把 Runner 接入 tailnet
      - name: setup Tailscale Connect (if needed)
        if: steps.check-ssh.outputs.keyless != 'true'
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret:    ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci     # 与 ACL 中的 tag 保持一致
          version: latest # https://pkgs.tailscale.com/stable/#static
          use-cache: 'true'

      # - name: Get containerd version
      #   run: |
      #     # pwd
      #     # ls 
      #     # ls setup-k8s/scripts
      #     source setup-k8s/scripts/functions.sh
      #     containerd_ver=$(get_github_latest_release containerd/containerd)
      #     # echo ${containerd_ver}
      #     containerd_ver=${containerd_ver/v/}
      #     # echo ${containerd_ver}
      #     echo "containerd_ver=${containerd_ver}" >> $GITHUB_ENV

      # - name: Cache containerd
      #   id:   cache-containerd
      #   uses: actions/cache@v4
      #   with:
      #     path: /tmp/containerd
      #     key: containerd-${containerd_ver}

      # - name: Download containerd (if cache miss)
      #   if: steps.cache-containerd.outputs.cache-hit != 'true'
      #   shell: bash -el {0}
      #   run: |
      #     source setup-k8s/scripts/functions.sh
      #     [ -d /tmp/containerd ] || mkdir /tmp/containerd
      #     wget "${GHPROXY}https://github.com/containerd/containerd/releases/download/v${containerd_ver}/containerd-${containerd_ver}-linux-amd64.tar.gz" -O /tmp/containerd/containerd-${containerd_ver}-linux-amd64.tar.gz
      #     curl ${GHPROXY}https://raw.githubusercontent.com/containerd/containerd/main/containerd.service -o /tmp/containerd/containerd.service

      #     runc_ver=$(get_github_latest_release opencontainers/runc)
      #     echo "runc_ver=${runc_ver}" >> $GITHUB_ENV
      #     wget ${GHPROXY}https://github.com/opencontainers/runc/releases/download/${runc_ver}/runc.amd64 -O /tmp/containerd/runc.amd64

      #     cni_ver=$(get_github_latest_release containernetworking/plugins)
      #     echo "cni_ver=${cni_ver}" >> $GITHUB_ENV
      #     wget ${GHPROXY}https://github.com/containernetworking/plugins/releases/download/${cni_ver}/cni-plugins-linux-amd64-${cni_ver}.tgz -O /tmp/containerd/cni-plugins-linux-amd64-${cni_ver}.tgz
          
      #     ls /tmp/containerd

      - name: install ansible
        run: |
          if ! command -v ansible &>/dev/null; then
            pip install ansible-core==2.18.3 netaddr 
            ansible-galaxy collection install ansible.posix \
              community.general \
              community.crypto \
              kubernetes.core \
              ansible.utils
          fi

      - name: download kubespray git repository
        run: |
          git clone https://github.com/kubernetes-sigs/kubespray.git
          cd kubespray/
          cp -rfp inventory/sample inventory/mycluster

      - name: Ansible inventory
        run: |
          cd $GITHUB_WORKSPACE/kubespray  # GITHUB_WORKSPACE=/home/runner/work/homelab-pve/homelab-pve
          # 2️⃣ 生成 Ansible inventory 文件
          # TODO: 也可以通过脚本动态生成 inventory.ini，支持更多节点和不同的用户
          tee inventory/mycluster/inventory.ini <<EOF
          [all]
          k8s-cp-01 ansible_host=10.10.10.11 ip=10.10.10.11 ansible_user=$VM_USER
          k8s-cp-02 ansible_host=10.10.10.12 ip=10.10.10.12 ansible_user=$VM_USER
          k8s-cp-03 ansible_host=10.10.10.13 ip=10.10.10.13 ansible_user=$VM_USER
          k8s-node-01 ansible_host=10.10.10.101 ip=10.10.10.101 ansible_user=$VM_USER
          k8s-node-02 ansible_host=10.10.10.102 ip=10.10.10.102 ansible_user=$VM_USER

          # 高可用组
          [etcd]
          k8s-cp-01
          k8s-cp-02
          k8s-cp-03

          [kube_control_plane]
          k8s-cp-01
          k8s-cp-02
          k8s-cp-03

          [kube_node]
          k8s-node-01
          k8s-node-02

          # 负载均衡器
          [lb]
          k8s-cp-01
          k8s-cp-02
          k8s-cp-03

          [k8s_cluster:children]
          kube_control_plane
          kube_node
          EOF

      - name: add registry host entry
        run: |
          cd $GITHUB_WORKSPACE/kubespray  # GITHUB_WORKSPACE=/home/runner/work/homelab-pve/homelab-pve
          # 3️⃣ 把 registry host 添加到所有节点的 /etc/hosts 中（如果需要的话）
          tee add-hosts-entry.yml <<'EOF'
          ---
          - name: Ensure registry host entry is present on all nodes
            hosts: all  # 或者使用 'k8s-cluster' 等特定组
            become: yes  # 修改 /etc/hosts 需要 root 权限
            tasks:
              - name: Add registry host entry to /etc/hosts
                ansible.builtin.lineinfile:
                  path: /etc/hosts
                  line: '10.10.10.1 pve.taile80cb.ts.net'
                  state: present
                  # 可选：使用正则表达式，确保不会重复添加
                  regexp: '^10\.10\.10\.1\s+pve\.taile80cb\.ts\.net'
          EOF

      - name: prepare offline packages and sync to registry (if needed)
        run: |
          cd $GITHUB_WORKSPACE/kubespray/contrib/offline  # GITHUB_WORKSPACE=/home/runner/work/homelab-pve/homelab-pve
          bash generate_list.sh
          # 创建下载目录
          mkdir -p temp/files
          mkdir -p temp/images
          # 下载所有二进制文件

          if skip_file != 'true'; then
            wget -x -P temp/files -i temp/files.list
          fi

          if skip_image != 'true'; then
            # 4️⃣ 把镜像同步到私有 registry 中（如果需要的话）
            for image in $(cat temp/images.list); do
              echo "### skopeo copy docker://${image} docker://${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }}:5000/k8s/${image#*/}"
              skopeo copy docker://${image} docker://${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }}:5000/k8s/${image#*/}
            done
          fi

      - name: prepare kubespray command on pve
        run: |
          cd $GITHUB_WORKSPACE # GITHUB_WORKSPACE=/home/runner/work/homelab-pve/homelab-pve
          tee main.sh <<'EOF'
          #!/bin/bash
          SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
          cd $SCRIPT_DIR

          ansible-playbook -i inventory/mycluster/inventory.ini add-hosts-entry.yml -b
          rsync -av /root/kubespray/contrib/offline/temp/files/* /usr/share/nginx/html/ 
          
          # nginx 默认的静态文件目录是 /usr/share/nginx/html/，默认的配置文件是 /etc/nginx/conf.d/default.conf
          # /etc/nginx/conf.d/default.conf
          # 开启目录列表功能
          # autoindex on;

          # 5️⃣ 修改 kubespray 的离线安装配置，指向私有 registry 和文件服务器
          OFFLINE_FILE="inventory/mycluster/group_vars/all/offline.yml"
          sed -i '/registry_host:/cregistry_host: "pve.taile80cb.ts.net:5000/k8s"' $OFFLINE_FILE
          sed -i '/files_repo:/cfiles_repo: "http://10.10.10.1"' $OFFLINE_FILE
          sed -i '/_image_repo/s/^# //g' $OFFLINE_FILE
          sed -i '/_download_url/s/^# //g' $OFFLINE_FILE

          # 6️⃣ 执行 kubespray 的安装命令
          ansible-playbook -i inventory/mycluster/inventory.ini cluster.yml -b -v
          EOF


      - name: sync kubespray to pve
        run: |
          cd $GITHUB_WORKSPACE # GITHUB_WORKSPACE=/home/runner/work/homelab-pve/homelab-pve
          rsync --rsync-path="sudo rsync" -e  'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -avz --partial --progress --inplace ./* root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }}:/root/kubespray/

      - name: debug
        run: |
          pwd
          # echo ${{ github.ref }}
          # env

      - name: setup k8s via kubespray
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} "bash /root/kubespray/main.sh"          